---
title: "Propuesta"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Nombre : Seminario Taller 

#### Objetivo

Dibulgación del uso de herramientas interactivas para la docencia que faciliten la enseñanza -  aprendizaje de los estudiantes de las matemáticas y la estadística

#### Periodicidad

Mensual

#### Lugar

Sala de computo - Laboratorio de matemáticas aplicadas
número de equipos : 9

#### Temas propuestos

* Uso de git - github 
* Construcción de página web con RStudio
* Construcción de tutoriales co RStudio
* Construcción de tutoriales con Python
* Uso de mentimeter como elemento de evaluación
* Uso de Patlet como herramienta de construcción de conocimiento
* Uso de overlef como herramienta para la consturcción de documetos de manera colaborativa
* Uso de geogebra como herramienta de simulación para la construcción de conceptos

#### Con quienes contamos

* Abel Alvarez
* Daniel Gonzalez
* Isabel Garcia
* David Arango
* Otros profesores invitados - invitarlos a partiipar y compartir
* Exalumnos de matematicas - realizar inventario

#### Fechas y temas 

|            |           |
|:-----------|:----------|
|Agosto      | Git       |
|Septiembre  | Git -R    |
|Octubre     | Git - Py  | 
|Noviembre   | Overleaf  |



#### Notas

* Las actividades seran grabadas y colocadas en plataforma, para posterior uso de los participantes

* Los interesados se deben inscribir, dependiendo la demanda se reprogramaran las sesiones








